### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by stryguardian** [blomstra/flarum-ext-digest#11]
I get this error when trying to install Digest.

Problem 1
    - Root composer.json requires blomstra/digest *, found blomstra/digest[dev-cw/subscriptions-notify-for-all-posts, dev-cw/repeat-follow-notifications, dev-cw/excludes, dev-master, 0.1.0-beta.1, ..., 0.1.0-beta.8] but it does not match your minimum-stability.

**Comment by luceos** [comment]
try `composer require blomstra/digest:"@beta"`

**Comment by stryguardian** [comment]
That worked!
